---------------------------------------------------------------------------
--- Generate a list of rectangles representing a layout, even when hidden
--
-- @author Emmanuel Lepage Vallee &lt;elv1313@gmail.com&gt;
-- @copyright 2016 Emmanuel Lepage Vallee
-- @release @AWESOME_VERSION@
-- @module awful.layout.dynamic.minimap
---------------------------------------------------------------------------

-- local module = {}

-- local function handle_hierarchy(h, wa)
--     local w = h:get_widget()
--
--     if widget._client then
--         local x, y = h:get_matrix_to_device():transform_point(0, 0)
--         widget._place_client(wa.x + x, wa.y + y, h:get_size())
--     end
--
--     for _, child in ipairs(h:get_children()) do
--         handle_hierarchy(child, wa)
--     end
-- end

-- local function get_rects(handler)
--     local ret = {}
-- 
--     --Move to the work area
--     local workarea = handler.param.workarea
-- 
--     local add_x, add_y = workarea.x, workarea.y
-- 
-- local function handle_hierarchy(h, wa)
--     local w = h:get_widget()
--
--     if widget._client then
--         local x, y = h:get_matrix_to_device():transform_point(0, 0)
--         widget._place_client(wa.x + x, wa.y + y, h:get_size())
--     end
--
--     for _, child in ipairs(h:get_children()) do
--         handle_hierarchy(child, wa)
--     end
-- end
-- 
--         for _, child in ipairs(h:get_children()) do
--             handle_hierarchy(child)
--         end
--     end
-- 
--     handle_hierarchy(handler.hierarchy)
-- 
--     return ret, workarea.width, workarea.height
-- end

-- local function scale_rects(rects, wa_w, wa_h, res_w, res_h)
--     --TODO
-- end

-- WORK IN PROGRESS
-- local function minimap(handler, width, height, floating)
--     local rects, wa_w, wa_h = get_rects(handler)
-- 
--     for k, rect in ipairs(rects) do
--         print("HELLO", rect.x, rect.x, rect.width, rect.height)
--     end
-- 
--     print("\n\nGENERATING MINIMAP!!!!")
-- end

-- return setmetatable(module, { __call = function(_, ...) return minimap(...) end })
